import type { CollectionConfig } from 'payload'

export const Aircraft: CollectionConfig = {
  slug: 'aircraft',
  admin: {
    useAsTitle: 'registration',
  },
  fields: [
    {
      name: 'organization',
      type: 'relationship',
      relationTo: 'organizations',
      required: true,
    },
    {
      name: 'name',
      type: 'text',
    },
    {
      name: 'registration',
      type: 'text',
      required: true,
    },
    {
      name: 'model',
      type: 'text',
      required: true,
    },
    {
      name: 'manufacturer',
      type: 'text',
    },
    {
      name: 'legalId',
      type: 'text',
    },
    {
      name: 'serialNumber',
      type: 'text',
    },
    {
      name: 'status',
      type: 'select',
      required: true,
      defaultValue: 'operational',
      options: [
        { label: 'Operational', value: 'operational' },
        { label: 'Inspection Due', value: 'inspection_due' },
        { label: 'Maintenance Due', value: 'maintenance_due' },
        { label: 'Grounded', value: 'grounded' },
        { label: 'Retired', value: 'retired' },
      ],
    },
    {
      name: 'flightHours',
      type: 'number',
      defaultValue: 0,
    },
    {
      name: 'flightCount',
      type: 'number',
      defaultValue: 0,
    },
    {
      name: 'aircraftType',
      type: 'select',
      defaultValue: 'multi_rotors',
      options: [
        { label: 'Multi-rotors', value: 'multi_rotors' },
        { label: 'Fixed wing', value: 'fixed_wing' },
        { label: 'VTOL', value: 'vtol' },
        { label: 'Helicopter', value: 'helicopter' },
        { label: 'Other', value: 'other' },
      ],
    },
    { name: 'internalSerial', type: 'text' },
    { name: 'flightControllerSerial', type: 'text' },
    { name: 'remoteControllerSerial', type: 'text' },
    { name: 'remoteController2Serial', type: 'text' },
    { name: 'softwareInformation', type: 'textarea' },
    { name: 'geometry', type: 'text' },
    { name: 'inventoryAssetNumber', type: 'text' },
    { name: 'description', type: 'textarea' },
    { name: 'tags', type: 'text' },
    { name: 'location', type: 'text' },
    { name: 'ownerLabel', type: 'text' },
    { name: 'complianceCategory', type: 'text' },
    { name: 'firmwareVersion', type: 'text' },
    { name: 'hardwareVersion', type: 'text' },
    {
      name: 'propulsionType',
      type: 'select',
      defaultValue: 'electric',
      options: [
        { label: 'Electric', value: 'electric' },
        { label: 'Hybrid', value: 'hybrid' },
        { label: 'Gas', value: 'gas' },
        { label: 'Other', value: 'other' },
      ],
    },
    { name: 'weightKg', type: 'number' },
    { name: 'maxGrossTakeoffKg', type: 'number' },
    { name: 'maxPayloadKg', type: 'number' },
    { name: 'color', type: 'text' },
    { name: 'maxSpeedMs', type: 'number' },
    { name: 'maxVerticalSpeedMs', type: 'number' },
    { name: 'maxFlightTimeSeconds', type: 'number' },
    { name: 'outOfSightDistance', type: 'number' },
    { name: 'purchaseDate', type: 'date' },
    { name: 'insurableValue', type: 'number' },
    { name: 'loanerDrone', type: 'checkbox', defaultValue: false },
    { name: 'excludedFromLegalReport', type: 'checkbox', defaultValue: false },
    { name: 'remoteId', type: 'text' },
    { name: 'connectivitySlot1', type: 'text' },
    { name: 'connectivitySlot1Extra', type: 'text' },
    { name: 'connectivitySlot2', type: 'text' },
    { name: 'connectivitySlot2Extra', type: 'text' },
    { name: 'videoSourceUrl', type: 'text' },
  ],
}
