/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    organizations: Organization;
    users: User;
    media: Media;
    projects: Project;
    missions: Mission;
    aircraft: Aircraft;
    components: Component;
    equipment: Equipment;
    batteries: Battery;
    'battery-charges': BatteryCharge;
    operators: Operator;
    flights: Flight;
    'flight-tracks': FlightTrack;
    incidents: Incident;
    'maintenance-records': MaintenanceRecord;
    inspections: Inspection;
    checklists: Checklist;
    'risk-assessments': RiskAssessment;
    notifications: Notification;
    documents: Document;
    'compliance-violations': ComplianceViolation;
    'audit-events': AuditEvent;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    organizations: OrganizationsSelect<false> | OrganizationsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    missions: MissionsSelect<false> | MissionsSelect<true>;
    aircraft: AircraftSelect<false> | AircraftSelect<true>;
    components: ComponentsSelect<false> | ComponentsSelect<true>;
    equipment: EquipmentSelect<false> | EquipmentSelect<true>;
    batteries: BatteriesSelect<false> | BatteriesSelect<true>;
    'battery-charges': BatteryChargesSelect<false> | BatteryChargesSelect<true>;
    operators: OperatorsSelect<false> | OperatorsSelect<true>;
    flights: FlightsSelect<false> | FlightsSelect<true>;
    'flight-tracks': FlightTracksSelect<false> | FlightTracksSelect<true>;
    incidents: IncidentsSelect<false> | IncidentsSelect<true>;
    'maintenance-records': MaintenanceRecordsSelect<false> | MaintenanceRecordsSelect<true>;
    inspections: InspectionsSelect<false> | InspectionsSelect<true>;
    checklists: ChecklistsSelect<false> | ChecklistsSelect<true>;
    'risk-assessments': RiskAssessmentsSelect<false> | RiskAssessmentsSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    'compliance-violations': ComplianceViolationsSelect<false> | ComplianceViolationsSelect<true>;
    'audit-events': AuditEventsSelect<false> | AuditEventsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations".
 */
export interface Organization {
  id: string;
  name: string;
  code: string;
  status: 'active' | 'inactive' | 'suspended';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  role: 'admin' | 'ops_manager' | 'pilot' | 'maintenance' | 'compliance' | 'viewer';
  organization?: (string | null) | Organization;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: string;
  organization: string | Organization;
  name: string;
  code: string;
  customer?: string | null;
  shared?: boolean | null;
  revenue?: number | null;
  status: 'active' | 'on_hold' | 'completed' | 'archived';
  location?: {
    lat?: number | null;
    lng?: number | null;
    label?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "missions".
 */
export interface Mission {
  id: string;
  organization: string | Organization;
  project?: (string | null) | Project;
  name: string;
  code: string;
  status: 'draft' | 'submitted' | 'under_review' | 'approved' | 'assigned' | 'in_progress' | 'completed' | 'closed';
  riskLevel?: ('low' | 'medium' | 'high' | 'critical') | null;
  boundaries?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  scheduledStart?: string | null;
  scheduledEnd?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "aircraft".
 */
export interface Aircraft {
  id: string;
  organization: string | Organization;
  name?: string | null;
  registration: string;
  model: string;
  manufacturer?: string | null;
  legalId?: string | null;
  serialNumber?: string | null;
  status: 'operational' | 'inspection_due' | 'maintenance_due' | 'grounded' | 'retired';
  flightHours?: number | null;
  flightCount?: number | null;
  aircraftType?: ('multi_rotors' | 'fixed_wing' | 'vtol' | 'helicopter' | 'other') | null;
  internalSerial?: string | null;
  flightControllerSerial?: string | null;
  remoteControllerSerial?: string | null;
  remoteController2Serial?: string | null;
  softwareInformation?: string | null;
  geometry?: string | null;
  inventoryAssetNumber?: string | null;
  description?: string | null;
  tags?: string | null;
  location?: string | null;
  ownerLabel?: string | null;
  complianceCategory?: string | null;
  firmwareVersion?: string | null;
  hardwareVersion?: string | null;
  propulsionType?: ('electric' | 'hybrid' | 'gas' | 'other') | null;
  weightKg?: number | null;
  maxGrossTakeoffKg?: number | null;
  maxPayloadKg?: number | null;
  color?: string | null;
  maxSpeedMs?: number | null;
  maxVerticalSpeedMs?: number | null;
  maxFlightTimeSeconds?: number | null;
  outOfSightDistance?: number | null;
  purchaseDate?: string | null;
  insurableValue?: number | null;
  loanerDrone?: boolean | null;
  excludedFromLegalReport?: boolean | null;
  remoteId?: string | null;
  connectivitySlot1?: string | null;
  connectivitySlot1Extra?: string | null;
  connectivitySlot2?: string | null;
  connectivitySlot2Extra?: string | null;
  videoSourceUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "components".
 */
export interface Component {
  id: string;
  organization: string | Organization;
  name: string;
  componentType:
    | 'motor'
    | 'propeller_cw'
    | 'propeller_ccw'
    | 'esc'
    | 'landing_gear'
    | 'arm'
    | 'flight_controller'
    | 'gnss'
    | 'other';
  manufacturer?: string | null;
  model?: string | null;
  serialNumber?: string | null;
  aircraft?: (string | null) | Aircraft;
  installationDate?: string | null;
  operatingHours?: number | null;
  flightCount?: number | null;
  replacementDate?: string | null;
  status: 'operational' | 'maintenance' | 'retired' | 'removed';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "equipment".
 */
export interface Equipment {
  id: string;
  organization: string | Organization;
  name: string;
  equipmentType:
    | 'camera'
    | 'gimbal'
    | 'lidar'
    | 'rtk'
    | 'charger'
    | 'case'
    | 'controller'
    | 'tablet'
    | 'ground_station'
    | 'survey'
    | 'gnss'
    | 'other';
  serialNumber?: string | null;
  manufacturer?: string | null;
  model?: string | null;
  assignedUser?: string | null;
  aircraft?: (string | null) | Aircraft;
  flightHours?: number | null;
  status: 'operational' | 'maintenance' | 'retired' | 'lost';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "batteries".
 */
export interface Battery {
  id: string;
  organization: string | Organization;
  name?: string | null;
  serialNumber: string;
  model?: string | null;
  legalId?: string | null;
  shared?: boolean | null;
  ownerLabel?: string | null;
  aircraft?: (string | null) | Aircraft;
  status: 'operational' | 'maintenance' | 'retired' | 'damaged';
  healthScore?: number | null;
  cycleCount?: number | null;
  cycleLifespan?: number | null;
  flightCount?: number | null;
  flightLifespan?: number | null;
  flightHours?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "battery-charges".
 */
export interface BatteryCharge {
  id: string;
  organization: string | Organization;
  battery: string | Battery;
  flight?: (string | null) | Flight;
  chargedAt: string;
  cycleNumber?: number | null;
  chargeLevel?: number | null;
  dischargeLevel?: number | null;
  healthScore?: number | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "flights".
 */
export interface Flight {
  id: string;
  organization: string | Organization;
  flightId: string;
  source?: string | null;
  sourceFlightId?: string | null;
  fingerprint?: string | null;
  startTime?: string | null;
  endTime?: string | null;
  durationMinutes?: number | null;
  pilot?: (string | null) | Operator;
  aircraft?: (string | null) | Aircraft;
  battery?: (string | null) | Battery;
  mission?: (string | null) | Mission;
  project?: (string | null) | Project;
  takeoff?: {
    lat?: number | null;
    lng?: number | null;
    alt?: number | null;
  };
  landing?: {
    lat?: number | null;
    lng?: number | null;
    alt?: number | null;
  };
  locationLabel?: string | null;
  tags?: ('trace' | 'event' | 'shared' | 'isolated')[] | null;
  distanceKm?: number | null;
  maxAltitudeM?: number | null;
  maxSpeedMs?: number | null;
  averageSpeedMs?: number | null;
  weather?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  status: 'planned' | 'active' | 'completed' | 'cancelled' | 'imported';
  flightTrackId?: string | null;
  rawStorageKey?: string | null;
  missionType?: string | null;
  operationType?: string | null;
  flightPurpose?: string | null;
  notes?: string | null;
  checklistStatus?: ('not_started' | 'complete' | 'incomplete' | 'violated') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "operators".
 */
export interface Operator {
  id: string;
  organization: string | Organization;
  user?: (string | null) | User;
  fullName: string;
  employeeId?: string | null;
  status: 'active' | 'inactive' | 'suspended';
  totalFlightHours?: number | null;
  currencyStatus: 'current' | 'expiring' | 'expired';
  role?: string | null;
  contactEmail?: string | null;
  contactPhone?: string | null;
  flightCount?: number | null;
  skills?: ('bvlos' | 'night' | 'thermal' | 'rtk' | 'dock' | 'survey' | 'lidar' | 'mapping' | 'inspection')[] | null;
  licenseExpiry?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "flight-tracks".
 */
export interface FlightTrack {
  id: string;
  organization: string | Organization;
  flight: string | Flight;
  geometry?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  pointCount?: number | null;
  simplified?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "incidents".
 */
export interface Incident {
  id: string;
  organization: string | Organization;
  title: string;
  cause?: string | null;
  severity: 'low' | 'medium' | 'high' | 'critical' | 'major';
  status: 'open' | 'under_review' | 'investigating' | 'resolved' | 'closed';
  shared?: boolean | null;
  personnelLabel?: string | null;
  locationLabel?: string | null;
  flight?: (string | null) | Flight;
  aircraft?: (string | null) | Aircraft;
  project?: (string | null) | Project;
  reportedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "maintenance-records".
 */
export interface MaintenanceRecord {
  id: string;
  organization: string | Organization;
  assetType: 'aircraft' | 'battery' | 'component' | 'equipment';
  assetId: string;
  title: string;
  status: 'overdue' | 'scheduled' | 'in_progress' | 'completed' | 'cancelled';
  dueLabel?: string | null;
  assetLabel?: string | null;
  dueDate?: string | null;
  completedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inspections".
 */
export interface Inspection {
  id: string;
  organization: string | Organization;
  assetType: 'aircraft' | 'battery' | 'component' | 'equipment';
  assetId: string;
  title: string;
  status: 'scheduled' | 'due' | 'overdue' | 'passed' | 'failed';
  dueDate?: string | null;
  completedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "checklists".
 */
export interface Checklist {
  id: string;
  organization: string | Organization;
  name: string;
  checklistType:
    | 'preflight'
    | 'postflight'
    | 'mission_prep'
    | 'aircraft_inspection'
    | 'equipment_inspection'
    | 'battery_inspection'
    | 'emergency'
    | 'site_ops'
    | 'custom';
  items?:
    | {
        label: string;
        itemType: 'pass_fail' | 'yes_no' | 'number' | 'text' | 'photo' | 'signature' | 'notes';
        required?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "risk-assessments".
 */
export interface RiskAssessment {
  id: string;
  organization: string | Organization;
  title: string;
  mission?: (string | null) | Mission;
  flight?: (string | null) | Flight;
  riskLevel: 'low' | 'medium' | 'high' | 'critical';
  status: 'draft' | 'submitted' | 'approved' | 'rejected';
  hazards?: string | null;
  mitigations?: string | null;
  responsiblePerson?: string | null;
  approvedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: string;
  organization: string | Organization;
  title: string;
  body?: string | null;
  type:
    | 'inspection_due'
    | 'inspection_overdue'
    | 'maintenance_due'
    | 'maintenance_overdue'
    | 'battery_cycle'
    | 'document_expiry'
    | 'pilot_cert_expiry'
    | 'checklist_missing'
    | 'compliance_violation'
    | 'incident'
    | 'mission_approval'
    | 'info';
  severity: 'info' | 'warning' | 'critical';
  read?: boolean | null;
  relatedEntityType?: string | null;
  relatedEntityId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: string;
  organization: string | Organization;
  title: string;
  documentType?: string | null;
  category?: ('flight' | 'pilot' | 'organization' | 'other') | null;
  reference?: string | null;
  holderName?: string | null;
  shared?: boolean | null;
  expiryDate?: string | null;
  storageKey?: string | null;
  linkedEntityType?: string | null;
  linkedEntityId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "compliance-violations".
 */
export interface ComplianceViolation {
  id: string;
  organization: string | Organization;
  severity: 'normal' | 'warning' | 'critical';
  ruleCode: string;
  message: string;
  entityType?: string | null;
  entityId?: string | null;
  status: 'open' | 'acknowledged' | 'resolved';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-events".
 */
export interface AuditEvent {
  id: string;
  organization: string | Organization;
  actorEmail?: string | null;
  action: string;
  entityType?: string | null;
  entityId?: string | null;
  previous?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  next?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  requestId?: string | null;
  ip?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'organizations';
        value: string | Organization;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'projects';
        value: string | Project;
      } | null)
    | ({
        relationTo: 'missions';
        value: string | Mission;
      } | null)
    | ({
        relationTo: 'aircraft';
        value: string | Aircraft;
      } | null)
    | ({
        relationTo: 'components';
        value: string | Component;
      } | null)
    | ({
        relationTo: 'equipment';
        value: string | Equipment;
      } | null)
    | ({
        relationTo: 'batteries';
        value: string | Battery;
      } | null)
    | ({
        relationTo: 'battery-charges';
        value: string | BatteryCharge;
      } | null)
    | ({
        relationTo: 'operators';
        value: string | Operator;
      } | null)
    | ({
        relationTo: 'flights';
        value: string | Flight;
      } | null)
    | ({
        relationTo: 'flight-tracks';
        value: string | FlightTrack;
      } | null)
    | ({
        relationTo: 'incidents';
        value: string | Incident;
      } | null)
    | ({
        relationTo: 'maintenance-records';
        value: string | MaintenanceRecord;
      } | null)
    | ({
        relationTo: 'inspections';
        value: string | Inspection;
      } | null)
    | ({
        relationTo: 'checklists';
        value: string | Checklist;
      } | null)
    | ({
        relationTo: 'risk-assessments';
        value: string | RiskAssessment;
      } | null)
    | ({
        relationTo: 'notifications';
        value: string | Notification;
      } | null)
    | ({
        relationTo: 'documents';
        value: string | Document;
      } | null)
    | ({
        relationTo: 'compliance-violations';
        value: string | ComplianceViolation;
      } | null)
    | ({
        relationTo: 'audit-events';
        value: string | AuditEvent;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations_select".
 */
export interface OrganizationsSelect<T extends boolean = true> {
  name?: T;
  code?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  organization?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  organization?: T;
  name?: T;
  code?: T;
  customer?: T;
  shared?: T;
  revenue?: T;
  status?: T;
  location?:
    | T
    | {
        lat?: T;
        lng?: T;
        label?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "missions_select".
 */
export interface MissionsSelect<T extends boolean = true> {
  organization?: T;
  project?: T;
  name?: T;
  code?: T;
  status?: T;
  riskLevel?: T;
  boundaries?: T;
  scheduledStart?: T;
  scheduledEnd?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "aircraft_select".
 */
export interface AircraftSelect<T extends boolean = true> {
  organization?: T;
  name?: T;
  registration?: T;
  model?: T;
  manufacturer?: T;
  legalId?: T;
  serialNumber?: T;
  status?: T;
  flightHours?: T;
  flightCount?: T;
  aircraftType?: T;
  internalSerial?: T;
  flightControllerSerial?: T;
  remoteControllerSerial?: T;
  remoteController2Serial?: T;
  softwareInformation?: T;
  geometry?: T;
  inventoryAssetNumber?: T;
  description?: T;
  tags?: T;
  location?: T;
  ownerLabel?: T;
  complianceCategory?: T;
  firmwareVersion?: T;
  hardwareVersion?: T;
  propulsionType?: T;
  weightKg?: T;
  maxGrossTakeoffKg?: T;
  maxPayloadKg?: T;
  color?: T;
  maxSpeedMs?: T;
  maxVerticalSpeedMs?: T;
  maxFlightTimeSeconds?: T;
  outOfSightDistance?: T;
  purchaseDate?: T;
  insurableValue?: T;
  loanerDrone?: T;
  excludedFromLegalReport?: T;
  remoteId?: T;
  connectivitySlot1?: T;
  connectivitySlot1Extra?: T;
  connectivitySlot2?: T;
  connectivitySlot2Extra?: T;
  videoSourceUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "components_select".
 */
export interface ComponentsSelect<T extends boolean = true> {
  organization?: T;
  name?: T;
  componentType?: T;
  manufacturer?: T;
  model?: T;
  serialNumber?: T;
  aircraft?: T;
  installationDate?: T;
  operatingHours?: T;
  flightCount?: T;
  replacementDate?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "equipment_select".
 */
export interface EquipmentSelect<T extends boolean = true> {
  organization?: T;
  name?: T;
  equipmentType?: T;
  serialNumber?: T;
  manufacturer?: T;
  model?: T;
  assignedUser?: T;
  aircraft?: T;
  flightHours?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "batteries_select".
 */
export interface BatteriesSelect<T extends boolean = true> {
  organization?: T;
  name?: T;
  serialNumber?: T;
  model?: T;
  legalId?: T;
  shared?: T;
  ownerLabel?: T;
  aircraft?: T;
  status?: T;
  healthScore?: T;
  cycleCount?: T;
  cycleLifespan?: T;
  flightCount?: T;
  flightLifespan?: T;
  flightHours?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "battery-charges_select".
 */
export interface BatteryChargesSelect<T extends boolean = true> {
  organization?: T;
  battery?: T;
  flight?: T;
  chargedAt?: T;
  cycleNumber?: T;
  chargeLevel?: T;
  dischargeLevel?: T;
  healthScore?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "operators_select".
 */
export interface OperatorsSelect<T extends boolean = true> {
  organization?: T;
  user?: T;
  fullName?: T;
  employeeId?: T;
  status?: T;
  totalFlightHours?: T;
  currencyStatus?: T;
  role?: T;
  contactEmail?: T;
  contactPhone?: T;
  flightCount?: T;
  skills?: T;
  licenseExpiry?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "flights_select".
 */
export interface FlightsSelect<T extends boolean = true> {
  organization?: T;
  flightId?: T;
  source?: T;
  sourceFlightId?: T;
  fingerprint?: T;
  startTime?: T;
  endTime?: T;
  durationMinutes?: T;
  pilot?: T;
  aircraft?: T;
  battery?: T;
  mission?: T;
  project?: T;
  takeoff?:
    | T
    | {
        lat?: T;
        lng?: T;
        alt?: T;
      };
  landing?:
    | T
    | {
        lat?: T;
        lng?: T;
        alt?: T;
      };
  locationLabel?: T;
  tags?: T;
  distanceKm?: T;
  maxAltitudeM?: T;
  maxSpeedMs?: T;
  averageSpeedMs?: T;
  weather?: T;
  status?: T;
  flightTrackId?: T;
  rawStorageKey?: T;
  missionType?: T;
  operationType?: T;
  flightPurpose?: T;
  notes?: T;
  checklistStatus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "flight-tracks_select".
 */
export interface FlightTracksSelect<T extends boolean = true> {
  organization?: T;
  flight?: T;
  geometry?: T;
  pointCount?: T;
  simplified?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "incidents_select".
 */
export interface IncidentsSelect<T extends boolean = true> {
  organization?: T;
  title?: T;
  cause?: T;
  severity?: T;
  status?: T;
  shared?: T;
  personnelLabel?: T;
  locationLabel?: T;
  flight?: T;
  aircraft?: T;
  project?: T;
  reportedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "maintenance-records_select".
 */
export interface MaintenanceRecordsSelect<T extends boolean = true> {
  organization?: T;
  assetType?: T;
  assetId?: T;
  title?: T;
  status?: T;
  dueLabel?: T;
  assetLabel?: T;
  dueDate?: T;
  completedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inspections_select".
 */
export interface InspectionsSelect<T extends boolean = true> {
  organization?: T;
  assetType?: T;
  assetId?: T;
  title?: T;
  status?: T;
  dueDate?: T;
  completedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "checklists_select".
 */
export interface ChecklistsSelect<T extends boolean = true> {
  organization?: T;
  name?: T;
  checklistType?: T;
  items?:
    | T
    | {
        label?: T;
        itemType?: T;
        required?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "risk-assessments_select".
 */
export interface RiskAssessmentsSelect<T extends boolean = true> {
  organization?: T;
  title?: T;
  mission?: T;
  flight?: T;
  riskLevel?: T;
  status?: T;
  hazards?: T;
  mitigations?: T;
  responsiblePerson?: T;
  approvedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  organization?: T;
  title?: T;
  body?: T;
  type?: T;
  severity?: T;
  read?: T;
  relatedEntityType?: T;
  relatedEntityId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  organization?: T;
  title?: T;
  documentType?: T;
  category?: T;
  reference?: T;
  holderName?: T;
  shared?: T;
  expiryDate?: T;
  storageKey?: T;
  linkedEntityType?: T;
  linkedEntityId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "compliance-violations_select".
 */
export interface ComplianceViolationsSelect<T extends boolean = true> {
  organization?: T;
  severity?: T;
  ruleCode?: T;
  message?: T;
  entityType?: T;
  entityId?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-events_select".
 */
export interface AuditEventsSelect<T extends boolean = true> {
  organization?: T;
  actorEmail?: T;
  action?: T;
  entityType?: T;
  entityId?: T;
  previous?: T;
  next?: T;
  requestId?: T;
  ip?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}